'use client'

import Link from 'next/link'
import { useState, useEffect } from 'react'
import {
  Zap, Shield, ArrowRight,
  CheckCircle, BarChart3, Award, Lock
} from 'lucide-react'

const STATS = [
  { value: '2,400+', label: 'Influencers' },
  { value: '850+', label: 'Brands' },
  { value: '₹4.2Cr+', label: 'Paid Out' },
  { value: '98%', label: 'Success Rate' },
]

const HOW_IT_WORKS_BRAND = [
  { step: '01', title: 'Register & Verify', desc: 'Create your brand profile. We verify you within 24 hours.' },
  { step: '02', title: 'Post a Gig', desc: 'Describe your campaign — type, niche, budget, deliverables. Pay ₹250 to activate.' },
  { step: '03', title: 'Discover & Pitch', desc: 'Browse matching influencers and send them collaboration pitches.' },
  { step: '04', title: 'Collab & Pay Securely', desc: 'Sign the agreement, deposit payment in escrow. Release funds only when satisfied.' },
]

const HOW_IT_WORKS_INFLUENCER = [
  { step: '01', title: 'Build Your Profile', desc: 'Add your social stats, niche, pricing, and past brand collabs.' },
  { step: '02', title: 'Get Discovered', desc: 'Brands find you through smart filters that match their campaign needs.' },
  { step: '03', title: 'Accept & Sign', desc: 'Review the brand\'s pitch, negotiate, and sign the platform agreement.' },
  { step: '04', title: 'Deliver & Get Paid', desc: 'Submit your deliverables. Payment releases automatically once approved.' },
]

const FEATURES = [
  {
    icon: Shield,
    title: 'Escrow Payment Protection',
    desc: 'Brands deposit funds upfront. You get paid only when the brand approves — full protection for both sides.',
    color: '#7C3AED',
  },
  {
    icon: BarChart3,
    title: 'Verified Social Stats',
    desc: 'Influencers add their real stats — followers, engagement, reach — so brands make informed decisions.',
    color: '#F59E0B',
  },
  {
    icon: Award,
    title: 'Smart Matching',
    desc: 'Our algorithm matches brands with influencers by niche, audience size, platforms, and collaboration type.',
    color: '#10B981',
  },
  {
    icon: Lock,
    title: 'Platform Agreement',
    desc: 'Every collaboration is backed by a legally structured agreement auto-generated by the platform.',
    color: '#3B82F6',
  },
]

const NICHES = ['Fashion', 'Beauty', 'Food', 'Travel', 'Fitness', 'Tech', 'Gaming', 'Lifestyle', 'Finance', 'Education']

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [activeTab, setActiveTab] = useState<'brand' | 'influencer'>('brand')
  const [scrolled, setScrolled] = useState(false)

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 40)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return (
    <div style={{ background: 'var(--bg-base)', minHeight: '100vh', overflow: 'hidden' }}>

      {/* Nav */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
        padding: '0 32px',
        background: scrolled ? 'rgba(10,10,15,0.95)' : 'transparent',
        backdropFilter: scrolled ? 'blur(16px)' : 'none',
        borderBottom: scrolled ? '1px solid var(--bg-border)' : 'none',
        transition: 'all 0.3s',
      }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 72 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{
              width: 36, height: 36, borderRadius: 10,
              background: 'var(--gradient-brand)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Zap size={18} color="white" fill="white" />
            </div>
            <span style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: 22, color: 'var(--text-primary)' }}>
              CollabKaro
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Link href="/login" className="btn btn-ghost" style={{ fontSize: 14 }}>Log in</Link>
            <Link href="/register" className="btn btn-primary" style={{ fontSize: 14 }}>
              Join Free
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section style={{
        minHeight: '100vh',
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        textAlign: 'center',
        padding: '120px 24px 80px',
        position: 'relative',
      }}>
        {/* Background glow */}
        <div style={{
          position: 'absolute', top: '30%', left: '50%', transform: 'translate(-50%, -50%)',
          width: 800, height: 800,
          background: 'radial-gradient(ellipse, rgba(124,58,237,0.12) 0%, transparent 70%)',
          pointerEvents: 'none',
        }} />

        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: 'rgba(124,58,237,0.1)', border: '1px solid rgba(124,58,237,0.3)',
          borderRadius: 100, padding: '6px 16px', marginBottom: 32,
          fontSize: 13, fontWeight: 600, color: '#A78BFA',
        }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#7C3AED', display: 'inline-block', animation: 'pulse 2s infinite' }} />
          India&apos;s Smartest Influencer Platform
        </div>

        <h1 style={{
          fontFamily: 'Syne, sans-serif', fontWeight: 800,
          fontSize: 'clamp(40px, 6vw, 80px)',
          lineHeight: 1.1, letterSpacing: '-0.03em',
          color: 'var(--text-primary)',
          maxWidth: 900, marginBottom: 24,
        }}>
          Where Brands Meet{' '}
          <span className="text-gradient">the Right</span>
          {' '}Creators
        </h1>

        <p style={{
          fontSize: 18, color: 'var(--text-secondary)', lineHeight: 1.7,
          maxWidth: 580, marginBottom: 48,
        }}>
          CollabKaro connects verified brands with top influencers across Instagram, YouTube, and beyond — with escrow payments, smart matching, and zero payment risk.
        </p>

        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', justifyContent: 'center', marginBottom: 72 }}>
          <Link href="/register/brand" className="btn btn-primary" style={{ padding: '14px 28px', fontSize: 15 }}>
            I&apos;m a Brand
            <ArrowRight size={16} />
          </Link>
          <Link href="/register/influencer" style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '14px 28px', fontSize: 15, fontWeight: 600,
            background: 'var(--bg-elevated)', border: '1px solid var(--bg-border)',
            borderRadius: 10, color: 'var(--text-primary)', textDecoration: 'none',
            transition: 'all 0.2s',
          }}>
            I&apos;m a Creator
            <ArrowRight size={16} />
          </Link>
        </div>

        {/* Stats */}
        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 24,
          maxWidth: 720, width: '100%',
        }}>
          {STATS.map((stat) => (
            <div key={stat.label} style={{ textAlign: 'center' }}>
              <div style={{
                fontFamily: 'Syne, sans-serif', fontWeight: 800,
                fontSize: 32, color: 'var(--text-primary)',
              }}>{stat.value}</div>
              <div style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Niches strip */}
      <div style={{
        borderTop: '1px solid var(--bg-border)', borderBottom: '1px solid var(--bg-border)',
        padding: '20px 0', overflow: 'hidden',
        background: 'var(--bg-surface)',
      }}>
        <div style={{ display: 'flex', gap: 32, padding: '0 32px', overflowX: 'auto', scrollbarWidth: 'none' }}>
          {[...NICHES, ...NICHES].map((niche, i) => (
            <span key={i} style={{
              fontSize: 13, fontWeight: 600, color: 'var(--text-muted)',
              whiteSpace: 'nowrap', letterSpacing: '0.05em', textTransform: 'uppercase',
            }}>
              {niche}
            </span>
          ))}
        </div>
      </div>

      {/* Features */}
      <section style={{ padding: '100px 24px', maxWidth: 1200, margin: '0 auto' }}>
        <div style={{ textAlign: 'center', marginBottom: 64 }}>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 48px)', fontWeight: 800, marginBottom: 16 }}>
            Built for trust. Designed for results.
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: 17, maxWidth: 520, margin: '0 auto' }}>
            Every feature exists to protect both sides of the collaboration.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 24 }}>
          {FEATURES.map((f) => (
            <div key={f.title} className="card" style={{ padding: 28 }}>
              <div style={{
                width: 48, height: 48, borderRadius: 12,
                background: `${f.color}20`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                marginBottom: 20,
              }}>
                <f.icon size={22} color={f.color} />
              </div>
              <h3 style={{ fontSize: 17, fontWeight: 700, marginBottom: 10 }}>{f.title}</h3>
              <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section style={{ padding: '80px 24px', background: 'var(--bg-surface)' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 48 }}>
            <h2 style={{ fontSize: 'clamp(26px, 3.5vw, 44px)', fontWeight: 800, marginBottom: 16 }}>
              How CollabKaro works
            </h2>

            <div style={{ display: 'inline-flex', background: 'var(--bg-elevated)', borderRadius: 12, padding: 4, gap: 4 }}>
              {(['brand', 'influencer'] as const).map((tab) => (
                <button key={tab} onClick={() => setActiveTab(tab)} style={{
                  padding: '8px 20px', borderRadius: 9, border: 'none', cursor: 'pointer',
                  fontFamily: 'Inter, sans-serif', fontWeight: 600, fontSize: 14,
                  background: activeTab === tab ? 'var(--brand-primary)' : 'transparent',
                  color: activeTab === tab ? 'white' : 'var(--text-secondary)',
                  transition: 'all 0.2s',
                }}>
                  {tab === 'brand' ? 'For Brands' : 'For Influencers'}
                </button>
              ))}
            </div>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 24 }}>
            {(activeTab === 'brand' ? HOW_IT_WORKS_BRAND : HOW_IT_WORKS_INFLUENCER).map((item) => (
              <div key={item.step} style={{ position: 'relative' }}>
                <div style={{
                  fontSize: 48, fontFamily: 'Syne, sans-serif', fontWeight: 800,
                  color: 'rgba(124,58,237,0.15)', lineHeight: 1, marginBottom: 12,
                }}>{item.step}</div>
                <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 8 }}>{item.title}</h3>
                <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing callout */}
      <section style={{ padding: '100px 24px' }}>
        <div style={{ maxWidth: 900, margin: '0 auto', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
          {/* Brand card */}
          <div className="card" style={{ padding: 36, position: 'relative', overflow: 'hidden' }}>
            <div style={{
              position: 'absolute', top: -40, right: -40,
              width: 160, height: 160,
              background: 'radial-gradient(ellipse, rgba(124,58,237,0.15) 0%, transparent 70%)',
            }} />
            <div style={{ fontSize: 13, fontWeight: 600, color: '#A78BFA', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '0.08em' }}>For Brands</div>
            <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: 42, color: 'var(--text-primary)', marginBottom: 4 }}>
              ₹250
            </div>
            <div style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 24 }}>per Gig posted</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {['Unlimited pitches to influencers', 'Escrow payment protection', 'Platform agreement included', 'Full collaboration management'].map((item) => (
                <div key={item} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <CheckCircle size={16} color="var(--success)" />
                  <span style={{ fontSize: 14, color: 'var(--text-secondary)' }}>{item}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Influencer card */}
          <div className="card" style={{ padding: 36, position: 'relative', overflow: 'hidden' }}>
            <div style={{
              position: 'absolute', top: -40, right: -40,
              width: 160, height: 160,
              background: 'radial-gradient(ellipse, rgba(245,158,11,0.15) 0%, transparent 70%)',
            }} />
            <div style={{ fontSize: 13, fontWeight: 600, color: '#FCD34D', marginBottom: 12, textTransform: 'uppercase', letterSpacing: '0.08em' }}>For Influencers</div>
            <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: 42, color: 'var(--text-primary)', marginBottom: 4 }}>
              10%
            </div>
            <div style={{ color: 'var(--text-muted)', fontSize: 14, marginBottom: 24 }}>platform commission only on paid collabs</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {['Free to join & build profile', 'Get discovered by top brands', 'Secure payment guarantee', 'Barter collabs 100% free'].map((item) => (
                <div key={item} style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <CheckCircle size={16} color="var(--success)" />
                  <span style={{ fontSize: 14, color: 'var(--text-secondary)' }}>{item}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{
        padding: '100px 24px',
        background: 'var(--bg-surface)',
        textAlign: 'center',
      }}>
        <div style={{ maxWidth: 640, margin: '0 auto' }}>
          <h2 style={{ fontSize: 'clamp(30px, 4vw, 52px)', fontWeight: 800, marginBottom: 20 }}>
            Ready to{' '}
            <span className="text-gradient">CollabKaro?</span>
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: 17, marginBottom: 40, lineHeight: 1.7 }}>
            Join thousands of brands and creators already building great things together.
          </p>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/register/brand" className="btn btn-primary" style={{ padding: '14px 28px', fontSize: 15 }}>
              Register as Brand <ArrowRight size={16} />
            </Link>
            <Link href="/register/influencer" style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              padding: '14px 28px', fontSize: 15, fontWeight: 600,
              background: 'var(--bg-elevated)', border: '1px solid var(--bg-border)',
              borderRadius: 10, color: 'var(--text-primary)', textDecoration: 'none',
            }}>
              Register as Influencer <ArrowRight size={16} />
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer style={{
        borderTop: '1px solid var(--bg-border)',
        padding: '32px 24px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexWrap: 'wrap', gap: 16,
        maxWidth: 1200, margin: '0 auto',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 28, height: 28, borderRadius: 8,
            background: 'var(--gradient-brand)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Zap size={14} color="white" fill="white" />
          </div>
          <span style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, fontSize: 16 }}>CollabKaro</span>
        </div>
        <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>
          © {new Date().getFullYear()} CollabKaro. All rights reserved.
        </p>
      </footer>

      <style jsx global>{`
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
      `}</style>
    </div>
  )
}